---
apiVersion: v1
kind: Namespace
metadata:
  name: app1-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab1
  namespace: app1-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab1
  template:
    metadata:
      labels:
        app: lab1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lab1-service
  namespace: app1-ns
spec:
  selector:
    app: lab1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80